# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bode/CLionProjects/encrypted-chat

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bode/CLionProjects/encrypted-chat

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bode/CLionProjects/encrypted-chat/CMakeFiles /home/bode/CLionProjects/encrypted-chat//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bode/CLionProjects/encrypted-chat/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bode/CLionProjects/encrypted-chat/CMakeFiles /home/bode/CLionProjects/encrypted-chat//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bode/CLionProjects/encrypted-chat/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named encrypted_chat

# Build rule for target.
encrypted_chat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 encrypted_chat
.PHONY : encrypted_chat

# fast build rule for target.
encrypted_chat/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encrypted_chat.dir/build.make CMakeFiles/encrypted_chat.dir/build
.PHONY : encrypted_chat/fast

p1.o: p1.c.o
.PHONY : p1.o

# target to build an object file
p1.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encrypted_chat.dir/build.make CMakeFiles/encrypted_chat.dir/p1.c.o
.PHONY : p1.c.o

p1.i: p1.c.i
.PHONY : p1.i

# target to preprocess a source file
p1.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encrypted_chat.dir/build.make CMakeFiles/encrypted_chat.dir/p1.c.i
.PHONY : p1.c.i

p1.s: p1.c.s
.PHONY : p1.s

# target to generate assembly for a file
p1.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encrypted_chat.dir/build.make CMakeFiles/encrypted_chat.dir/p1.c.s
.PHONY : p1.c.s

p2.o: p2.c.o
.PHONY : p2.o

# target to build an object file
p2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encrypted_chat.dir/build.make CMakeFiles/encrypted_chat.dir/p2.c.o
.PHONY : p2.c.o

p2.i: p2.c.i
.PHONY : p2.i

# target to preprocess a source file
p2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encrypted_chat.dir/build.make CMakeFiles/encrypted_chat.dir/p2.c.i
.PHONY : p2.c.i

p2.s: p2.c.s
.PHONY : p2.s

# target to generate assembly for a file
p2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encrypted_chat.dir/build.make CMakeFiles/encrypted_chat.dir/p2.c.s
.PHONY : p2.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... encrypted_chat"
	@echo "... p1.o"
	@echo "... p1.i"
	@echo "... p1.s"
	@echo "... p2.o"
	@echo "... p2.i"
	@echo "... p2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

